### PR TITLE
feat: allow register CLI to create a public register writable to anyone

### PR DESCRIPTION
**Pull request by thomasmarkiewicz**
### Summary generated by Reviewpad on 05 Jan 24 22:32 UTC
This pull request includes changes in various files. Here is a summary of the changes:

1. In the file "nodes_rewards.rs":
- Imported the `Permissions` struct from the `sn_registers` module.
- Modified the `create_and_pay_for_register` function call by adding a new argument `Permissions::new_owner_only()`.
These changes involve using the `Permissions` struct and passing it as an argument to the `create_and_pay_for_register` function.

2. In the file "register.rs":
- Removed the `create_public_online` function.
- Modified the `create_online` function to accept a `perms` parameter of type `Permissions`.
- The `perms` parameter is used in `create_register` when creating the register.
These changes suggest a refactoring of the code related to creating and syncing registers in the client.

3. In the file "Cargo.lock":
- Added the "sn_registers" dependency.

4. In the file "data_with_churn.rs":
- Added an import statement for `Permissions` from the `sn_registers` module.
- Passed an additional argument `Permissions::new_owner_only()` to the `create_and_pay_for_register` function.
These changes seem to be related to enhancing security and permissions in the code.

5. In the file "registers.rs":
- Added an import statement for `Permissions` from the `sn_registers` module.
- Added the `Permissions::new_anyone_can_write()` as an additional parameter in the `create_and_pay_for_register` function call.
These changes indicate that the code now includes permissions for the register and allows anyone to write to it.

6. In the file "register.rs":
- Imported the `Permissions` struct from the `sn_registers` module.
- Added a new command line option `-p` or `--public` to create the register with public write access.
- Updated the `create_register` function to accept the `public` parameter and use it to determine the permissions of the register.
- Updated the `create_and_pay_for_register` function call to include the `perms` parameter.
- Print the address of the created register at the end.

7. In the file "Cargo.toml":
- Added a new dependency, "sn_registers", with version "0.3.6" in the "sn_cli" directory.

8. In the file "storage_payments.rs":
- Imported `sn_registers::Permissions`.
- Added additional arguments in the `create_and_pay_for_register` function call.
- Added creation of `Permissions::new_owner_only()`.
- Added additional arguments in the second `create_and_pay_for_register` function call.
These changes introduce the `Permissions` module, modify the function calls to `create_and_pay_for_register`, and add extra arguments to these function calls.

Let me know if you need any further assistance.
 

Resolves issue #1106

### CODE REVIEW

**Comment by joshuef** [comment]
Ah, thanks for reopening this! @thomasmarkiewicz .

Looks like this will need a rebase before CI can run though 🙇

**Comment by thomasmarkiewicz** [comment]
> Ah, thanks for reopening this! @thomasmarkiewicz .
> 
> Looks like this will need a rebase before CI can run though 🙇

Rebased, but bunch of jobs are "stuck" in waiting status

**Review by joshuef — APPROVED** [review]

**Comment by joshuef** [comment]
Hmm, not sure why these are still stuck 🤔 Right now the branch is up to date... Haven't seen this before, I'll have a poke about...

**Comment by joshuef** [comment]
Ahh, github unhelpfully hiding the error.

It's an issue with the merge workflow file: https://github.com/maidsafe/safe_network/actions/runs/7459237658?pr=1144

**Comment by thomasmarkiewicz** [comment]
I think it's close, but 3 checks are still stuck and I can't tell why

**Comment by RolandSherwin** [comment]
Hey @joshuef, looks like we might have to update the `expected test signature` for the E2E test here. 
The workflow file contains a new `safe_path` variable, which might be the reason.

**Review by RolandSherwin — APPROVED** [review]
Looks great! Approved 😄

**Pull request merged**
