### PR TITLE
Create tea.yaml

### PR DESCRIPTION
**Pull request by masprs0x**
# https://tea.xyz/what-is-this-file
---
version: 1.0.0
codeOwners:
  - '0x3231F7e657566101B6489A99482F56C616680717'
  - '0xAD2e10c20Fb9acDc8A51B432827e800102D8cc73' quorum: 1

## Description

reviewpad:summary

### CODE REVIEW

**Comment by masprs0x** [comment]
# https://tea.xyz/what-is-this-file
---
version: 1.0.0
codeOwners:
  - '0x3231F7e657566101B6489A99482F56C616680717'
  - '0xAD2e10c20Fb9acDc8A51B432827e800102D8cc73'
quorum: 1

**Review by JasonPaulGithub — CHANGES_REQUESTED** [review]
What is this doing exactly?

**Comment by JasonPaulGithub** [comment]
@joshuef 
Is this a tracker being adding to the Maidsafe project to gain rewards on something called teaRank?
If so. That's bold 😆 

https://docs.tea.xyz/tea/i-want-to.../begin-earning-tea-and-interact-with-the-protocol/registering-an-oss-project#why-verify-ownership

**Comment by masprs0x** [comment]
add as a contributor for next project tea testnet sir
if you need to see thats project
here https://app.tea.xyz/my-projects

thanks if you add me as contributor


Pada Sen, 11 Mar 2024 19.32, Jason Paul ***@***.***> menulis:

**Pull request closed without merging**
