### PR TITLE
ci: re-add disk space debugging

### PR DESCRIPTION
**Pull request by jacderida**
I would still like to monitor how much disk space `release-plz` is using just to see if upgrading to the new version has likely solved the problem we were having.

## Description

reviewpad:summary

### CODE REVIEW

**Comment by happybeing** [comment]
`vdash` too would love to see a log message that restores the disk use stats of old. Something like space used and available would be great.

**Comment by happybeing** [comment]
Ah, it's just merged and not in sn_node after all - sorry. As you were!

**Comment by jacderida** [comment]
> Ah, it's just merged and not in sn_node after all - sorry. As you were!

Yeah sorry, this is just a little bit of debugging output to the release process because we were having some trouble with a massive amount of disk space being used during our publishing process. Maybe you might want to follow that request up with Josh?

**Comment by happybeing** [comment]
Thanks Chris, I have pestered Josh about this enough I think! Just misunderstood this PR and jumped the gun :smile:

**Pull request merged**
