### PR TITLE
move mod.rs files the modern way

### PR DESCRIPTION
**Pull request by loziniak**
## Description

Move module files as suggested by Rust documentation.

https://safenetforum.org/t/safenet-client-api-module-structure/39202

reviewpad:summary

### CODE REVIEW

**Comment by joshuef** [comment]
One file is off there it seems! (otherwise, looking very nice, thanks @loziniak !)

**Comment by loziniak** [comment]
Are you talking about the [failing](https://github.com/maidsafe/safe_network/actions/runs/7893676918/job/21542766123?pr=1305) `cargo clippy --all-targets --all-features -- -Dwarnings` in *various checks* job? It's strange, because `sn_node/tests/common/mod.rs` is moved to `sn_node/tests/common.rs`, just as in any other place. Do you think it's treated differently in tests, perhaps?

**Comment by loziniak** [comment]
Indeed, `cargo test` on *sn_node* fails, but I don't understand it. When I did `cargo build` on *sn_cli*, it worked, and in *sn_client/src/files* module there is a similar structure, `pub(crate) mod download;` in *files.rs*, and a *sn_client/src/files/download.rs* with module's code...

**Comment by loziniak** [comment]
Ok, it seems this is an [exception](https://doc.rust-lang.org/stable/book/ch11-03-test-organization.html#submodules-in-integration-tests). Fix underway :-)

**Review by joshuef — APPROVED** [review]
perfect! 🙇 thanks heaps!

**Pull request merged**
