### PR TITLE
chore(auditor): set repository field in cargo

### PR DESCRIPTION
**Pull request by Foorack**
Update [repository](https://rust-digger.code-maven.com/about-repository) field in `Cargo.toml` to point to the GitHub repo.

This makes the location of the source code show correctly on Crates.io. 🙂

### CODE REVIEW

**Review by joshuef — APPROVED** [review]

**Comment by joshuef** [comment]
Thanks for this! Looking good. One thing:

We use conventional commits, please update your commit message, eg `chore(auditor): update repository field in cargo.toml` 

More info: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Foorack** [comment]
@joshuef Thanks, fixed! Will look for that in the future!

I don't have permission to re-run the CI job "Check before merge / lint". Do you want me to rebase branch to trigger it, you to re-run the job, or merge anyway?

**Comment by JasonPaulGithub** [comment]
Hi Foorack,
If you remove punctuation and capitalization from the commit message it should be good to go through. 
Thanks for your help!

**Comment by Foorack** [comment]
Hi @JasonPaulGithub 👋 

Thanks a lot, I had already removed any capitalization, but now I tried to remove the dot as well.

**Comment by RolandSherwin** [comment]
Hey @Foorack , you might have to update the `git commit message` as it still reads the following: 
```
sn_auditor: Update repository field in Cargo.toml
```

You can type the following command in your terminal to edit the message,
```
1. git commit --amend
2. edit the message
3. save it
4. git push Foorack cargo-toml  -f (or) force push it from your IDE
```

**Comment by Foorack** [comment]
Thank you @RolandSherwin ! That clears up the misunderstanding. I thought the CI verified the PR title, not the commit title.

Amended the commit and force pushed. Apologies for the confusion and extra work. Thanks for following up with me on this.

**Pull request merged**
